version: "3"
services:
  clockhat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    logging:
      options:
        max-size: 200mb
    restart: unless-stopped
